name: spatialcore
channels:
  - conda-forge
dependencies:
  - python=3.10
  - anndata
  - scanpy
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
      - -e .
